#!/usr/bin/env php
<?php

/*
 * This file is a part of the ConsoleApplication library.
 *
 * (c) 2014 Ebidtech
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

// Require the bootstrap file.
require __DIR__ . '/bootstrap.php';

// Load the command application.
$application = new \ConsoleApplication\Console\ConsoleApplication($container);
$application->run();
